# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Niciforovic's blog
email: david.r.niciforovic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is David Newman, but I'm better known as David Niciforovic.
  I dabble in indie game development as well as web development and
  design. I'm 26 and programming is my life. If I'm not busting out
  code, I'm probably not conscience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: datatype_void
github_username:  datatypevoid

# Build settings
markdown: kramdown
theme: minima
gems:
  - autoprefixer-rails
  - bootstrap
  - jekyll-assets
  - jekyll-feed
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
sass:
  #style: compressed
  sass_dir: _sass

# Other
repository: datatypevoid/datatypevoid.github.io
google_analytics: true
google_analytics_id: 'UA-73809333-2'
